### ISSUE TITLE
[BUG] Client have a bug.

### ISSUE THREAD

**Issue by RubyKiss** [Linko-3D/Godot-Simple-Networking#3]
When 2 clients enter the server and 1 player is below the other, then when moving left or right it appears that the player on top is automatically following the player on the bottom. What is the problem? I added collisionshape2d to player.tscn. Is this the problem?

**Comment by Linko-3D** [comment]
Hello, I have updated it with 3d players. Tell me if you still have the bug.
A change I have done is using rpc_id with a value of 1 to call the fonction add_player so only the servers adds it then it is synchronized.

**Comment by RubyKiss** [comment]
> Hello, I have updated it with 3d players. Tell me if you still have the bug. A change I have done is using rpc_id with a value of 1 to call the fonction add_player so only the servers adds it then it is synchronized.

It's still a problem.

it's just like this image
![image](https://github.com/user-attachments/assets/7e3abd38-3029-4b01-b48e-bd57cb5e5979)

The player below moves the one above follows.

**Comment by RubyKiss** [comment]
> Hello, I have updated it with 3d players. Tell me if you still have the bug. A change I have done is using rpc_id with a value of 1 to call the fonction add_player so only the servers adds it then it is synchronized.

maybe it is gravirty question

**Comment by Linko-3D** [comment]
It is normal that it stays on top, it also means that the character can stay on a moving platform.

**Comment by RubyKiss** [comment]
> It is normal that it stays on top, it also means that the character can stay on a moving platform.

how can i made it can't move ?

**Comment by Linko-3D** [comment]
You can disable collision between players, I have updated it.

**Comment by RubyKiss** [comment]
> You can disable collision between players, I have updated it.

yes i can. and then close this .
